### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by jaonoctus** [coredna/atom-phpfmt#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [phpfmt](https://github.com/coredna/atom-phpfmt) package, v1.0.0
### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At C:\Users\João Vítor Dias\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1043

Error: Can't save buffer with no file path
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\João Vítor Dias\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1043:15)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\João Vítor Dias\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\João Vítor Dias\AppData\Local\atom\app-1.4.0\resources\app.asar\src\text-editor.js:602:26)
    at Object.module.exports.PhpFmt.format (file:///C:/Users/João Vítor Dias/.atom/packages/phpfmt/lib/phpfmt.coffee:183:16)
    at atom-workspace.subscriptions.add.atom.commands.add.phpfmt:format (file:///C:/Users/João Vítor Dias/.atom/packages/phpfmt/lib/phpfmt.coffee:103:85)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\João Vítor Dias\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\João Vítor Dias\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\João Vítor Dias\AppData\Local\atom\app-1.4.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\João Vítor Dias\AppData\Local\atom\app-1.4.0\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -4:24.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:35.8.0 core:close (atom-text-editor.editor.is-focused)
     -1:31.8.0 settings-view:open (atom-pane.pane.active)
     -1:23.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:22.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:46 editor:newline (atom-text-editor.editor.is-focused)
     -0:41 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:41 snippets:expand (atom-text-editor.editor.is-focused)
     -0:40.9.0 editor:indent (atom-text-editor.editor.is-focused)
  6x -0:39.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:29.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:28 editor:newline (atom-text-editor.editor.is-focused)
     -0:22.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:17.4.0 grammar-selector:show (atom-text-editor.editor)
  3x -0:12.9.0 phpfmt:format (a.inline-block)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
hyperclick-php, v0.2.1
minimap, v4.19.0
phpfmt, v1.0.0

# Dev
No dev packages
```

**Comment by sjdaws** [comment]
Hi Joa,

Is this a file which hasn't been saved yet? Due to limitations currently in place the file has to exist on the disk, it can't be read directly from the buffer.
